//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelMVCUI.Models.EntitiyFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PersonelTb
    {
        public int PersonelID { get; set; }
        [Display(Name ="Personel Ad")]
        [Required(ErrorMessage ="Personel Adý alanýný doldurunuz")]
        public string PersoneAd { get; set; }
        [Display(Name = "Personel Ad")]
        [Required(ErrorMessage = "Personel Adý alanýný doldurunuz")]
        public string PersonelSoyad { get; set; }
        [Display(Name = "Departmanlar")]
        [Required(ErrorMessage = "Lütfen bir departman seçiniz")]
        public Nullable<int> DepartmanID { get; set; }
        [Display(Name = "Maaþ")]
        [Required(ErrorMessage = "Maaþ alanýný doldurunuz")]
        public Nullable<short> Maas { get; set; }
        [Display(Name = "Doðum Tarihi")]
        [Required(ErrorMessage = "Doðum tarihi alanýný doldurunuz")]
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public bool Cinsiyet { get; set; }
        public bool EvliMi { get; set; }
    
        public virtual DepartmanTb DepartmanTb { get; set; }
    }
}
